#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <directory>"
    exit 1
fi

directory="$1"

if [ ! -d "$directory" ]; then
    echo "Error: '$directory' is not a directory"
    exit 1
fi

find "$directory" -type f -path "*javadocs*" -name "*.html" | while read -r file; do
    sed -i.bak \
        -e 's/<!-- Generated by.*-->/<!-- EXCLUDED FROM COMPARISON -->/' \
        -e 's/<meta name="dc\.created" content=".*">/<!-- EXCLUDED FROM COMPARISON -->/' \
        "$file"
    rm "${file}.bak"
    [ -n "$VERBOSE" ] && echo "Processed: $file"
done
